version: "3"

services:
  lifewindpaneladmin:
    container_name: lifewindpaneladmin
    tty: true
    volumes:
      - ./:/app
    build:
      dockerfile: Dockerfile.local
    restart: unless-stopped
    ports:
      - "8080:8080"
